# render.yaml
services:
  - type: web
    name: phishguard-api
    runtime: python
    repo: https://github.com/batool004/phishing3
    buildCommand: pip install -r requirements.txt
    startCommand: python smart_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0